# -*- coding: utf-8 -*-
# Function to save topics to files

import os
import csv
from preprocess import *
from viz import *

def save_topics_to_files(lda_model, num_topics):
    """
    Saves the topics generated by the LDA model into text and CSV files.
    """
    topics = lda_model.show_topics(num_topics=num_topics, formatted=False)
    topics_data = [{"Topic": i, "Words": [word[0] for word in topic]} for i, topic in topics]

    # Save to text file
    txt_path = os.path.join(RESULT_FOLDER, 'topics.txt')
    with open(txt_path, 'w', encoding='utf-8') as f:
        for topic in topics_data:
            f.write(f"Topic {topic['Topic']}:\n")
            f.write(", ".join(topic['Words']) + "\n\n")

    # Save to CSV file
    csv_path = os.path.join(RESULT_FOLDER, 'topics.csv')
    with open(csv_path, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Topic', 'Words'])
        for topic in topics_data:
            writer.writerow([topic['Topic'], ", ".join(topic['Words'])])

    return txt_path, csv_path